# Generated by Django 6.0 on 2026-01-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['data', 'hora'],
                'unique_together': {('data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clientes.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.servico')),
                ('disponibilidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='agendamentos.disponibilidade')),
            ],
            options={
                'ordering': ['disponibilidade__data', 'disponibilidade__hora'],
            },
        ),
    ]
